### PR TITLE
fix overflow/underflow bug in zeta(z)

### LINKED ISSUE #128: over/underflow in zeta for complex argumetns
As reported [on discourse](https://discourse.julialang.org/t/possible-issue-with-zeta-function/16802) by @ArchieCall
```jl
julia> zeta(.4 + 453.0im)
NaN + NaN*im
```
The error seems to be triggered by this line:
https://github.com/JuliaMath/SpecialFunctions.jl/blob/803c96955356995d4d063a87e876961033502cbd/src/gamma.jl#L412

In particular, the problem is the `gamma(1 - s) * sinpi(s*0.5)` expression in the reflection formula.  If `s` has a large imaginary part, this is the product of an exponentially small with an exponentially large term.   Eventually, `gamma` underflows and `sinpi` overflows, giving `0*Inf = NaN`.

The solution would be to refactor the exponential terms and cancel them analytically.

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #128.

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -475,11 +475,17 @@ end
...
     @test 1e-13 > relerrc(zeta(1e-4 + 2e-4im), -0.5000918637469642920007659467492165281457662206388959645-0.0001838278317660822408234942825686513084009527096442173056im)
 
-    # Issue #7169: (TODO: better accuracy should be possible?)
-    @test 1e-9  > relerrc(zeta(0 + 99.69im), 4.67192766128949471267133846066040655597942700322077493021802+3.89448062985266025394674304029984849370377607524207984092848im)
+    # Issue #7169:
+    @test 1e-13  > relerrc(zeta(0 + 99.69im), 4.67192766128949471267133846066040655597942700322077493021802+3.89448062985266025394674304029984849370377607524207984092848im)
     @test 1e-12 > relerrc(zeta(3 + 99.69im), 1.09996958148566565003471336713642736202442134876588828500-0.00948220959478852115901654819402390826992494044787958181148im)
-    @test 1e-9  > relerrc(zeta(-3 + 99.69im), 10332.6267578711852982128675093428012860119184786399673520976+13212.8641740351391796168658602382583730208014957452167440726im)
+    @test 1e-13  > relerrc(zeta(-3 + 99.69im), 10332.6267578711852982128675093428012860119184786399673520976+13212.8641740351391796168658602382583730208014957452167440726im)
```
Comment (stevengj) [inline test/runtests.jl]: This PR also seems to have greatly improved the accuracy in this older test.

File: test/runtests.jl [hunk 2]
```diff
@@ -475,11 +475,17 @@ end
...
     @test 1e-13 > relerrc(zeta(2 + 99.69im, 1.3), 0.41617652544777996034143623540420694985469543821307918291931-0.74199610821536326325073784018327392143031681111201859489991im)
+
+    # issue #128
+    @test 1e-13 > relerrc(zeta(.4 + 453.0im), 5.595631794716693 - 4.994584420588448im)
+    @test 1e-10 > relerrc(zeta(.4 + 4053.0im), -0.1248993234383550+0.9195498409364987im)
```
Comment (stevengj) [inline test/runtests.jl]: In general, our current zeta algorithm is problematic for very large imaginary arguments.

Comment (chakravala) [reply test/runtests.jl]: It seems to be problematic for imaginary numbers greater than `10im`, so the issues start early.
