### PR TITLE
bigfloat erfinv and erfcinv

### LINKED ISSUE #277: erfcinv does not support BigFloat
erfc supports BigFloat, but not erfcinv:

ERROR: MethodError: no method matching erfcinv(::BigFloat)
Closest candidates are:
  erfcinv(::Missing) at /home/fabien/.julia/packages/SpecialFunctions/qmwwl/src/SpecialFunctions.jl:77
  erfcinv(::Float32) at /home/fabien/.julia/packages/SpecialFunctions/qmwwl/src/erf.jl:394
  erfcinv(::Float64) at /home/fabien/.julia/packages/SpecialFunctions/qmwwl/src/erf.jl:342

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #277.

### CODE REVIEW

**Comment by stevengj** [comment]
CI failure on nightly seems unrelated.

File: src/erf.jl [hunk 1]
```diff
@@ -413,7 +415,55 @@ function erfcinv(y::Float32)
...
+    sqrtπ = sqrt(big(pi))
+    if isfinite(xfloat)
+        x = BigFloat(xfloat)
+    else
+        # Float64 overflowed, use asymptotic estimate instead
+        # from erfc(x) ≈ exp(-x²)/x√π ≈ y  ⟹  -log(yπ) ≈ x² + log(x) ≈ x²
+        if yfloat < 1
+            x = sqrt(-log(y*sqrtπ))
+        else # y must be close to 2
+            @show x = -sqrt(-log((2-y)*sqrtπ))
```
Comment (musm) [inline src/erf.jl:451]:
```suggestion
            x = -sqrt(-log((2-y)*sqrtπ))
```

File: src/erf.jl [hunk 2]
```diff
@@ -413,7 +415,55 @@ function erfcinv(y::Float32)
...
+    xfloat = erfinv(Float64(y))
+    sqrtπ = sqrt(big(pi))
+    if isfinite(xfloat)
+        x = BigFloat(xfloat)
+    else
+        # Float64 overflowed, use asymptotic estimate instead
+        # from erfc(x) ≈ exp(-x²)/x√π ≈ y  ⟹  -log(yπ) ≈ x² + log(x) ≈ x²
+        x = copysign(sqrt(-log((1-abs(y))*sqrtπ)), y)
+    end
+    isfinite(x) || return x
```
Comment (musm) [inline src/erf.jl:428]: should this be moved into the end of the else block? 

`isfinite(xfloat)` will already ensure `x` in L422 is finite, so this looks like it's checking `isfinite(x)` twice in that case. Not a big deal, but thought I'd mention.

Comment (stevengj) [reply src/erf.jl:428]: You need both checks because xfloat might overflow even if the result is representable as bigfloat

File: src/erf.jl (hunk 1 above)
Comment (stevengj) [reply src/erf.jl:451]: Whoops, sorry

File: src/erf.jl (hunk 2 above)
Comment (musm) [reply src/erf.jl:428]: I'm not sure if I was clear (I might have worded tings confusingly). I was hoping to say:
why don't you move `isfinite(x) || return x` right after L426, instead of after the `if...else...end`  block.

Comment (stevengj) [reply src/erf.jl:428]: Yes, that would work.

File: src/erf.jl (hunk 1 above)
Comment (stevengj) [reply src/erf.jl:451]: Fixed in 4e8836c55eacae2f8d063f9d0702f741a1376211

File: src/erf.jl (hunk 2 above)
Comment (stevengj) [reply src/erf.jl:428]: Fixed in cdd323d00a4fc4b6dc93c41cf24406f0b7208e5d
