### PR TITLE
Underflow without erroring in beta_inc

### LINKED ISSUE #334: incomplete beta (beta_inc) function fails
I found the `beta_inc` function fails to calculate when it converges to one as its second argument (beta) grows:
```julia
julia> beta_inc(0.1, 1000.0, 0.2)
(1.0, 1.0943262485580365e-100)

julia> beta_inc(0.1, 2000.0, 0.2)
(1.0, 7.227539215122656e-198)

julia> beta_inc(0.1, 3000.0, 0.2)
(1.0, 6.1767167323400926e-295)

julia> beta_inc(0.1, 4000.0, 0.2)
ERROR: expansion can't be computed
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] beta_inc_asymptotic_asymmetric(a::Float64, b::Float64, x::Float64, y::Float64, w::Float64, epps::Float64)
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/Bm58S/src/beta_inc.jl:382
 [3] beta_inc(a::Float64, b::Float64, x::Float64, y::Float64)
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/Bm58S/src/beta_inc.jl:839
 [4] beta_inc(a::Float64, b::Float64, x::Float64)
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/Bm58S/src/beta_inc.jl:879
 [5] top-level scope
   @ REPL[55]:1
```

I confirmed this problem on SpecialFunctions.jl v1.5.1.

By the way, SciPy returns some value as follows:
```julia
In [3]: import scipy.special

In [4]: scipy.special.betainc(0.1, 4000.0, 0.2)
Out[4]: 0.9999999999999999
```

### PR DESCRIPTION
**Pull request by andreasnoack**
when there is a big difference between the parameters.

Fixes #334 the therefore the downstream issues https://github.com/FixedEffects/FixedEffectModels.jl/issues/192 and https://github.com/JuliaStats/StatsFuns.jl/issues/134

### CODE REVIEW

**Comment by devmotion** [comment]
There are two still other `error` statements in the function, shouldn't we handle them in the same way ?

**Comment by andreasnoack** [comment]
I've made similar changes to the other branch but I don't think it's possible to reach the first location via `beta_inc` and I can't come up with an example that reaches the third location so I haven't added tests for those branches.

File: src/beta_inc.jl [hunk 1]
```diff
@@ -371,19 +371,21 @@ function beta_inc_asymptotic_asymmetric(a::Float64, b::Float64, x::Float64, y::F
     end
     z = -nu*lnx
     if b*z == 0.0
-        return error("expansion can't be computed")
+        @debug("underflow: expansion can't be computed")
+        return w + b*z
```
Comment (devmotion) [inline src/beta_inc.jl:375]: Since all variables are of type `Float64`, it seems we could also just write
```suggestion
        return w
```

File: src/beta_inc.jl [hunk 2]
```diff
@@ -371,19 +371,21 @@ function beta_inc_asymptotic_asymmetric(a::Float64, b::Float64, x::Float64, y::F
...
     #SET R = EXP(-Z)*Z**B/GAMMA(B)
     r = b*(1.0 + rgamma1pm1(b))*exp(b*log(z))
     r *= exp(a*lnx)*exp(0.5*bm1*lnx)
-    u = loggammadiv(b,a) + b*log(nu)
+    u = loggammadiv(b, a) + b*log(nu)
     u = r*exp(-u)
     if u == 0.0
-        return error("expansion can't be computed")
+        @debug("underflow: expansion can't be computed")
+        return w + u
```
Comment (devmotion) [inline src/beta_inc.jl:386]: Similarly, here it seems we could write
```suggestion
        return w
```

File: src/beta_inc.jl [hunk 3]
```diff
@@ -412,7 +414,8 @@ function beta_inc_asymptotic_asymmetric(a::Float64, b::Float64, x::Float64, y::F
         dj = d[n] * j
         sm += dj
         if sm <= 0.0
-            return error("expansion can't be computed")
+            @debug("underflow: expansion can't be computed")
+            return w + sm
```
Comment (devmotion) [inline src/beta_inc.jl:418]: Is it useful to possibly subtract something from `w`? Otherwise we could write
```suggestion
            return w
```

File: src/beta_inc.jl (hunk 1 above)
Comment (andreasnoack) [reply src/beta_inc.jl]: Ah yes. Old promotion habits. I've fixed it.

**Review by devmotion — APPROVED** [review]
