### PR TITLE
expint: fixes for #263

### LINKED ISSUE #263: more expint bugs
cc @augustt198:
```jl
julia> expint(-2.1, 4.2 +0im)
ERROR: DomainError with -2.1:
`gamma(x)` must be non-negative
Stacktrace:
 [1] loggamma at /Users/stevenj/.julia/dev/SpecialFunctions/src/gamma.jl:666 [inlined]
 [2] En_imagbranchcut(::Float64, ::Complex{Float64}) at /Users/stevenj/.julia/dev/SpecialFunctions/src/expint.jl:349
 [3] expint(::Float64, ::Complex{Float64}, ::Int64) at /Users/stevenj/.julia/dev/SpecialFunctions/src/expint.jl:439
 [4] expint(::Float64, ::Complex{Float64}) at /Users/stevenj/.julia/dev/SpecialFunctions/src/expint.jl:364
 [5] top-level scope at REPL[2]:1

julia> expint(-2.1+3im, 4.2 +0im)
0.0033875656264970673 - 457824.4771614065im
```
The first error is spurious, and the second answer is wrong.

A possible fix:
```diff
diff --git a/src/expint.jl b/src/expint.jl
index b4baaec..e562060 100644
--- a/src/expint.jl
+++ b/src/expint.jl
@@ -346,7 +346,8 @@ function En_imagbranchcut(ν::Number, z::Number)
     a = real(z)
     e1 = exp(π*imag(ν))
     e2 = Complex(cospi(real(ν)), -sinpi(real(ν)))
-    impart = π * im * e1 * e2 * exp((ν-1)*log(complex(a)) - loggamma(ν))
+    lgamma, lgamma_sign = logabsgamma(ν)
+    impart = π * e1 * e2 * lgamma_sign * exp((ν-1)*log(complex(a)) - lgamma) * im
     impart *= signbit(imag(z)) ? -1 : 1
     return imag(impart) * im # get rid of any real error
 end
@@ -434,8 +435,8 @@ function expint(ν::Number, z::Number, niter::Int=1000)
             z₀ += Δ
         end
 
-        # more exact imaginary part available for non-integer ν
-        if imz == 0
+        # more exact imaginary part available for non-integer real ν
+        if imz == 0 && isreal(ν)
             E_start = real(E_start) + En_imagbranchcut(ν, z)
         end
```

At a more fundamental level, I'm concerned that the "z near the negative real axis" expansion is being used at all here (since `real(z) > 0`).  It seems like we should first try whether `En_cf` or `En_cf_nogamma` converge quickly, and only if that fails (and only for `real(z) < 0`) switch to the expansion.   (Also, it seems like the `quick_niter` threshold should depend on the precision.)

### PR DESCRIPTION
**Pull request by augustt198**
fixes #263

### CODE REVIEW

File: test/expint.jl [hunk 1]
```diff
@@ -76,6 +76,8 @@ using Base.MathConstants
         @test expint(-2, -3.3) ≅ -4.745485121488663825992363318400378114254141655964565963
         @test expint(-2, -3.3) isa Real
 
+        @test expint(-2.1+3im, 4.2 +0im) ⩭ 0.003387565626497080536855067510744646235748203589175196673362104 - 0.003355838600814825542988272289126728631565803782052141768321840im
```
Comment (stevengj) [inline test/expint.jl:79]: Include tests for `expint(-2.1+3im, -4.2)` and `expint(-2.1+3im, 4.2 +1im)`

File: src/expint.jl [hunk 2]
```diff
@@ -344,11 +344,10 @@ end
...
 function En_imagbranchcut(ν::Number, z::Number)
     a = real(z)
-    e1 = exp(π*imag(ν))
+    e1 = exp(oftype(a, π) * imag(ν))
     e2 = Complex(cospi(real(ν)), -sinpi(real(ν)))
-    impart = π * im * e1 * e2 * exp((ν-1)*log(complex(a)) - loggamma(ν))
-    impart *= signbit(imag(z)) ? -1 : 1
-    return imag(impart) * im # get rid of any real error
+    bc = -2 * e1 * π * e2 * exp((ν-1)*log(complex(a)) - loggamma(ν)) * im
+    return bc
```
Comment (stevengj) [inline src/expint.jl:350]: I would just `return -2 * e1 * ....`  … no need to define a variable `bc`.

File: test/expint.jl (hunk 1 above)
Comment (stevengj) [reply test/expint.jl:79]: Also tests for  `z=4.2-0im` to make sure the branch cut is handled correctly.

File: src/expint.jl [hunk 3]
```diff
@@ -344,11 +344,10 @@ end
 # https://functions.wolfram.com/GammaBetaErf/ExpIntegralE/04/05/01/0003/
 function En_imagbranchcut(ν::Number, z::Number)
     a = real(z)
-    e1 = exp(π*imag(ν))
+    e1 = exp(oftype(a, π) * imag(ν))
     e2 = Complex(cospi(real(ν)), -sinpi(real(ν)))
-    impart = π * im * e1 * e2 * exp((ν-1)*log(complex(a)) - loggamma(ν))
-    impart *= signbit(imag(z)) ? -1 : 1
-    return imag(impart) * im # get rid of any real error
+    bc = -2 * e1 * π * e2 * exp((ν-1)*log(complex(a)) - loggamma(ν)) * im
```
Comment (stevengj) [inline src/expint.jl:349]: Needs `logabsgamma` when `ν` is `Real`.

File: test/expint.jl [hunk 4]
```diff
@@ -76,6 +76,10 @@ using Base.MathConstants
...
+        @test expint(-4.3, -10+0.0im) ⩭ -1505.2167858114105916067190408869152177781925766866637213104 + 0.00015439438628349460776476190593323691084185406009267711345841im
+        @test expint(-4.3, -10-0.0im) ⩭ -1505.2167858114105916067190408869152177781925766866637213104 - 0.00015439438628349460776476190593323691084185406009267711345841im
```
Comment (stevengj) [inline test/expint.jl:81]: Also test `expint(-4.3+1im, -10±0.0im)`
