### PR TITLE
fix type-instability of logabsbeta

### LINKED ISSUE #331: logbeta is type-unstable
```jl
julia> @code_warntype logbeta(0.2, 0.3)
Variables
  #self#::Core.Const(SpecialFunctions.logbeta)
  a::Float64
  b::Float64
  @_4::Int64
  sign::Union{Int32, Int64}
  lab::Union{Float64, Int32, Int64}

Body::Union{Float64, Int32, Int64}
1 ─ %1  = SpecialFunctions.logabsbeta(a, b)::Tuple{Union{Float64, Int32, Int64}, Union{Int32, Int64}}
│   %2  = Base.indexed_iterate(%1, 1)::Core.PartialStruct(Tuple{Union{Float64, Int32, Int64}, Int64}, Any[Union{Float64, Int32, Int64}, Core.Const(2)])
│         (lab = Core.getfield(%2, 1))
│         (@_4 = Core.getfield(%2, 2))
│   %5  = Base.indexed_iterate(%1, 2, @_4::Core.Const(2))::Core.PartialStruct(Tuple{Union{Int32, Int64}, Int64}, Any[Union{Int32, Int64}, Core.Const(3)])
│         (sign = Core.getfield(%5, 1))
│   %7  = (sign < 0)::Bool
└──       goto #3 if not %7
2 ─ %9  = Core.tuple(a, b)::Tuple{Float64, Float64}
│   %10 = SpecialFunctions.DomainError(%9, "`beta(a, b)` must be non-negative")::Any
└──       SpecialFunctions.throw(%10)
3 ┄       return lab
```

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #331.

Also omit an `Int` conversion for `iseven` in Julia ≥ 1.7 (JuliaLang/julia#38976)

### CODE REVIEW

File: src/gamma.jl [hunk 1]
```diff
@@ -825,7 +826,7 @@ function logabsbeta(a::T, b::T) where T<:Real
     ya, sa = logabsgamma(a)
     yb, sb = logabsgamma(b)
     yab, sab = logabsgamma(a + b)
-    (ya + yb - yab), (sa*sb*sab)
+    (ya + yb - yab), Int(sa*sb*sab)
```
Comment (devmotion) [inline src/gamma.jl:829]: It seems another possible fix would be to ensure that `logabsgamma` always returns a sign of type `Int`. And I wonder if `logabsgamma` is type unstable as well.

Comment (stevengj) [reply src/gamma.jl:829]: `logabsgamma` is type-stable, but it returns `Int32` since that is what the C library returns.

Comment (stevengj) [reply src/gamma.jl:829]: We could change `logabsgamma` to return `Int`, of course.

Comment (stevengj) [reply src/gamma.jl:829]: Update: I changed `logabsgamma` to return `Int` for the sign also.   Just for consistency (the old code was type-stable), and because `Int` is the default type so using `Int32` might lead to other problems like the one in `logbeta`.

**Review by devmotion — APPROVED** [review]
