### PR TITLE
Fix condition in __gamma_inc_inv to ensure that sqrt argument in

### LINKED ISSUE #385: `gamma_inc_inv` throws an DomainError for valid arguments
First observed in https://github.com/JuliaStats/Distributions.jl/issues/1510:

```julia
julia> using SpecialFunctions

julia> gamma_inc_inv(0.010316813105574363, 1-0.010101010101010102, 0.010101010101010102)
ERROR: DomainError with -5.912352019184924:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(f::Symbol, x::Float64)
   @ Base.Math ./math.jl:33
 [2] sqrt
   @ ./math.jl:567 [inlined]
 [3] gamma_inc_inv_qsmall(a::Float64, q::Float64)
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/9pXme/src/gamma_inc.jl:707
 [4] __gamma_inc_inv(a::Float64, minpq::Float64, pcase::Bool)
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/9pXme/src/gamma_inc.jl:945
 [5] _gamma_inc_inv
   @ ~/.julia/packages/SpecialFunctions/9pXme/src/gamma_inc.jl:933 [inlined]
 [6] gamma_inc_inv(a::Float64, p::Float64, q::Float64)
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/9pXme/src/gamma_inc.jl:915
 [7] top-level scope
   @ REPL[12]:1

(jl_j536nH) pkg> st
      Status `/tmp/jl_j536nH/Project.toml`
  [276daf66] SpecialFunctions v2.1.2
```
The same error occurs also in SpecialFunctions 2.0.0, so it wasn't introduced by https://github.com/JuliaMath/SpecialFunctions.jl/pull/377.

### PR DESCRIPTION
**Pull request by andreasnoack**
`gamma_inc_inv_qsmall` is positive.

It wasn't obvious from the paper how to fix this and I verified that the original Fortran code gave the same wrong result. So to fix this, I simply took the argument to `log` in https://github.com/JuliaMath/SpecialFunctions.jl/blob/8b4aba0324737b1cee3807e8d63a746d0d74cbe9/src/gamma_inc.jl#L707 and solved the inequality ensuring that it's less than one.

Fixes #385.

### CODE REVIEW

File: src/gamma_inc.jl [hunk 1]
```diff
@@ -941,17 +941,23 @@ function __gamma_inc_inv(a::Float64, minpq::Float64, pcase::Bool)
...
+        elseif abs(minpq - 0.5) < 1.0e-05
+            x0 = a - 1.0/3.0 + (8.0/405.0 + 184.0/25515.0/a)/a
+        elseif abs(a - 1.0) < 1.0e-4
+            x0 = pcase ? -log1p(-minpq) : -log(minpq)
+        elseif a < 1.0 # small value of a
+            x0 = exp(logr)
+        else    #large a
+            haseta = true
+            x0, fp = gamma_inc_inv_alarge(a, minpq, pcase)
+        end
```
Comment (devmotion) [inline src/gamma_inc.jl:960]: Maybe we can optimize this a bit and also add an additional argument to `gamm_inc_inv_qsmall` such that the argument to the `log` in the `sqrt` expression does not have to be recomputed:
 ```suggestion
      # This deviates from the original version. The tmp variable
      # here ensures that the argument of sqrt in gamma_inc_inv_qsmall
      # is positive
      elseif !pcase && minpq < 0.02 && a < 10 && (tmp =  q*gammax(a)*sqrt(twoπ/a)) < 1 #small q
            x0 = gamma_inc_inv_qsmall(a, minpq, tmp)
      elseif abs(minpq - 0.5) < 1.0e-05
          x0 = a - 1.0/3.0 + (8.0/405.0 + 184.0/25515.0/a)/a
      elseif abs(a - 1.0) < 1.0e-4
          x0 = pcase ? -log1p(-minpq) : -log(minpq)
      elseif a < 1.0 # small value of a
          x0 = exp(logr)
      else    #large a
          haseta = true
          x0, fp = gamma_inc_inv_alarge(a, minpq, pcase)
```

**Review by devmotion — COMMENTED** [review]
I think this is the most natural fix. My only suggestion is avoiding to compute `tmp` (or its inverse) twice and in cases where the other conditions are not satisfied.

**Comment by andreasnoack** [comment]
I've made the suggested changes. I've also made a `backport` label which we can try to use to keep track of things that should be backported. It's probably a good idea that we get this fix shipped pretty soon since the bug might affects a lot of people now that Distributions uses this functions. It'll be interesting to see if more bugs are revealed with the extra number of users.

**Review by devmotion — APPROVED** [review]
Looks good to me.

Is there a particular reason you chose to compute `invgammaxa` instead of directly `q/invgammaxa = minpq/invgammaxa`? I thought that would save one operation (one `*` instead of `/` and `inv`).

**Comment by andreasnoack** [comment]
> Is there a particular reason you chose to compute invgammaxa instead of directly q/invgammaxa = minpq/invgammaxa?

Probably just to keep the condition as close to the original but I now see that you proposed a slightly different version. I've updated the PR accordingly.

**Review by devmotion — APPROVED** [review]
