### PR TITLE
missing promotion methods for loggammadiv

### LINKED ISSUE #239: MethodError: no method matching loggammadiv(::Int64, ::Int64) for beta with a >> b
https://github.com/JuliaMath/SpecialFunctions.jl/blob/1bb0913fc667d6aebbc2e29fc111cd3cb8629771/src/gamma.jl#L771

julia> beta(1000001, 1)
ERROR: MethodError: no method matching loggammadiv(::Int64, ::Int64)
Stacktrace:
 [1] beta(::Int64, ::Int64) at /Users/mfairley/.julia/packages/SpecialFunctions/LC8dm/src/gamma.jl:790
 [2] top-level scope at REPL[25]:1

### PR DESCRIPTION
**Pull request by stevengj**
Should fix #239.

cc @MFairley.

### CODE REVIEW

File: src/beta_inc.jl [hunk 1]
```diff
@@ -9,7 +9,10 @@ const exparg_p =  log(prevfloat(floatmax(Float64)))
 
 Computes ``log(\\Gamma(b)/\\Gamma(a+b))`` when b >= 8
 """
-function loggammadiv(a::Float64, b::Float64)
+loggammadiv(a::Number, b::Number) = _loggammadiv(float(a), float(b))
+
+_loggammadiv(a::T, b::T) where {T<:Base.IEEEFloat} = T(_loggammadiv(Float64(a), Float64(b)) # handle Float16, Float32
```
Comment (ararslan) [inline src/beta_inc.jl:14]:
```suggestion
_loggammadiv(a::T, b::T) where {T<:Base.IEEEFloat} = T(_loggammadiv(Float64(a), Float64(b))) # handle Float16, Float32
```
