### PR TITLE
Avoid negative initial x0 in gamma_inc_inv_qsmall. When the initial

### LINKED ISSUE #387: Another gamma_inc_inv failure
After #385 I'm trying to expand the testing of `gamma_inc_inv` and I already hit another case. This is again a case where the original Fortran version also fails.

```julia
julia> a, p, q = 1.0e-20, 1.0, 7.756625260915455e-21
(1.0e-20, 1.0, 7.756625260915455e-21)

julia> gamma_inc_inv(a, p, q)
ERROR: DomainError with -7.70608462508679:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(f::Symbol, x::Float64)
   @ Base.Math ./math.jl:33
 [2] _log(x::Float64, base::Val{:ℯ}, func::Symbol)
   @ Base.Math ./special/log.jl:304
 [3] log
   @ ./special/log.jl:269 [inlined]
 [4] __gamma_inc_inv(a::Float64, minpq::Float64, pcase::Bool)
   @ SpecialFunctions ~/.julia/dev/SpecialFunctions/src/gamma_inc.jl:969
 [5] _gamma_inc_inv
   @ ~/.julia/dev/SpecialFunctions/src/gamma_inc.jl:933 [inlined]
 [6] gamma_inc_inv(a::Float64, p::Float64, q::Float64)
   @ SpecialFunctions ~/.julia/dev/SpecialFunctions/src/gamma_inc.jl:915
 [7] top-level scope
   @ REPL[9]:1
```

### PR DESCRIPTION
**Pull request by andreasnoack**
x0 value is less than one, the updates in gamma_inc_inv_qsmall could
make the initial guess negative whith could make the Newton iteration
fail.

Also, expand the tests of gamma_inc_inv.

Fixes #387

### CODE REVIEW

File: src/gamma_inc.jl [hunk 1]
```diff
@@ -715,7 +715,9 @@ function gamma_inc_inv_qsmall(a::Float64, q::Float64, qgammaxa::Float64)
         ck3 = (@horner(l, @horner(b, -12, -24, -11), @horner(b, 12, 24, 6), @horner(b, -6, -9), 2))/6.0
         ck4 = (@horner(l, @horner(b, 72, 162, 120, 25), @horner(b, -72, -168, -114, -12), @horner(b, 36, 84, 36), @horner(b, -12, -22), 3))/12.0
         x0 = x0 - l + b*r*@horner(r, ck1, ck2, ck3, ck4)
-    else
+    elseif x0 > 1
+        # The x0 > 1 condition isn't in the original version but without it
+        # the update in the branch can cause negative initial x0
```
Comment (devmotion) [inline src/gamma_inc.jl:720]: I wonder if adding more terms (`ck2` etc.) as in the other branch would be an alternative. And what is lost by not updating `x0`.

Comment (andreasnoack) [reply src/gamma_inc.jl:720]: I tried that a bit but it doesn't seem to help so I'm wondering if the expansion is only valid/useful when x0 > 1. Notice that the the first branch, which uses more terms, requires x0 to be even larger. It is just for choosing the starting value for the Newton iterations so I think the worst consequence could be that slightly more iterations are required.

**Review by devmotion — APPROVED** [review]
