### PR TITLE
expint: Type stability, NaNs

### LINKED ISSUE #246: expint type instabilty for negative order
This is inconsistent: `expint(-n::Integer, x::Real)` should return a real result:
```jl
julia> expint(-2, 3.4)
0.01728780216752084 + 0.0im

julia> expint(-2, -3.4)
ERROR: DomainError with -3.4:
En will only return a complex result if called with a complex argument
Stacktrace:
 [1] expint(::Int64, ::Float64, ::Int64) at /Users/stevenj/.julia/dev/SpecialFunctions/src/expint.jl:385
 [2] expint(::Int64, ::Float64) at /Users/stevenj/.julia/dev/SpecialFunctions/src/expint.jl:380
 [3] top-level scope at REPL[8]:1

julia> expint(2, 3.4)
0.006543960041402119
```
(This is type-unstable, since the return type depends on the *value* of the order ±2 rather than the type.)

Also this
```jl
julia> expint(-2.2, 3.3)
ERROR: DomainError with -2.2:
`gamma(x)` must be non-negative
```
should probably throw the "En will only return a complex result if called with a complex argument" error instead.

cc @augustt198

### LINKED ISSUE #247: Expint hangs for complex NaN values
@fmeulen

### PR DESCRIPTION
**Pull request by augustt198**
Fixes #247.  Fixes #246.

### CODE REVIEW

File: src/expint.jl [hunk 1]
```diff
@@ -380,22 +386,24 @@ function expint(ν::Number, z::Number, niter::Int=1000)
     if abs(ν) > 50 && !(isreal(ν) && real(ν) > 0)
         throw(ArgumentError("Unsupported order |ν| > 50 off the positive real axis"))
     end
-    ν, z = promote(ν, float(z))
-    if typeof(z) <: Real && z < 0
+
+    z, = promote(float(z), ν)
+    if isnan(ν) || isnan(z)
+        return oftype(z, NaN)
```
Comment (stevengj) [inline src/expint.jl:392]: Maybe `oftype(z, NaN) * z` to make it return `NaN + NaN*im` in the complex case.

File: src/expint.jl [hunk 2]
```diff
@@ -424,7 +431,7 @@ function expint(ν::Number, z::Number, niter::Int=1000)
         
         quick_niter, nmax = 50, 45
         # start with small imaginary part if exactly on negative real axis
-        imstart = (imz == 0) ? abs(z)*1e-8 : imz
+        imstart = (imz == 0) ? abs(z)*sqrt(eps(real(z))) : imz
```
Comment (stevengj) [inline src/expint.jl:434]: `sqrt(eps(typeof(real(z))))`

File: test/expint.jl [hunk 3]
```diff
@@ -63,6 +63,11 @@ using Base.MathConstants
         @test expint(100000, 10+10im) ⩭ -3.8087890502240534e-10 + 2.470010601657554e-10im
         @test expint(1000000, 10+10im) ⩭ -3.8093198659567175e-11 + 2.4698678867697097e-11im
 
+        @test expint(-2, 3.3) ≅ 0.0200031425174657791728529428002375552480803611197081245457722070
+        @test expint(-2, 3.3) isa Real
+        @test expint(-2, -3.3) ≅ -4.745485121488663825992363318400378114254141655964565963
+        @test expint(-2, -3.3) isa Real
```
Comment (stevengj) [inline test/expint.jl:69]: add real and complex NaN tests?

**Review by stevengj — APPROVED** [review]
